### ISSUE TITLE
401 Error initializing data stores on wsbackend-tasknode

### ISSUE THREAD

**Issue by cjohnson-bf** [lavalamp-/ws-docker-community#2]
Greetings,

I'm getting a python stack trace while initializing data stores. I opened a shell on the wsbackend-tasknode container to look closer:

```
ubuntu@websight:~/ws-docker-community$ sudo docker exec -it 8cfe2d7f794a /bin/bash
root@8cfe2d7f794a:/ws-backend# python manage.py shell -c "from lib import bootstrap_data_stores; bootstrap_data_stores()"
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 95, in handle
    exec(options['command'])
  File "<string>", line 1, in <module>
  File "/ws-backend/lib/bootstrap.py", line 31, in bootstrap_data_stores
    bootstrap_elasticsearch()
  File "/ws-backend/lib/bootstrap.py", line 51, in bootstrap_elasticsearch
    update_model_mappings()
  File "/ws-backend/wselasticsearch/bootstrap.py", line 50, in update_model_mappings
    bootstrap_index_model_mappings(index=config.es_default_index, delete_first=delete_first)
  File "/ws-backend/wselasticsearch/bootstrap.py", line 31, in bootstrap_index_model_mappings
    indices = es_helper.get_indices()
  File "/ws-backend/wselasticsearch/helper.py", line 242, in get_indices
    return self.connection.indices.get_alias().keys()
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 399, in get_alias
    '_alias', name), params=params)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 89, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 124, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.AuthenticationException: TransportError(401, u'security_exception', u'missing authentication token for REST request [/_alias]')
```

I double checked to make sure the network info and creds for my elasticsearch is correct in tasknode.cfg:

```
[Elasticsearch]

es_username = elastic
es_password = changeme
es_host = 172.17.0.1
es_port = 9200
es_use_aws = False
```

I tested it from the container using curl and I don't get a 401:

```
root@8cfe2d7f794a:/ws-backend# curl --user elastic:changeme http://172.17.0.1:9200
{
  "name" : "YB_71OE",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha5",
    "build_hash" : "d327dd4",
    "build_date" : "2016-08-04T08:59:39.568Z",
    "build_snapshot" : false,
    "lucene_version" : "6.1.0"
  },
  "tagline" : "You Know, for Search"
}
```

...so I must be doing something wrong. I poked around at the code a little bit but nothing jumped out at me. Any hints/guidance would be much appreciated.

**Comment by lavalamp-** [comment]
Iiiiiinteresting... I'll take a look at this in a bit - thanks for pointing it out!

**Comment by lavalamp-** [comment]
So it looks like this is due to the fact that I haven't actually written anything to use username+password in Elasticsearch yet... Which strikes me as odd. As shown below the Elasticsearch client is instantiated without using any credentials:

```
def __get_standard_es_connection(self):
    """
    Create a new standard Elasticsearch connection and return it.
    :return: An Elasticsearch connection.
    """
    if config.http_proxy_enabled:
        proxies = {
            "http": config.http_proxy,
            "https": config.http_proxy,
        }
    else:
        proxies = {}
    return Elasticsearch(
        [config.es_url],
        connection_class=WsElasticsearchConnection,
        proxies=proxies,
    )
```

Try disabling authentication in your Elasticsearch server and seeing if that fixes the issue. I'll look into adding the authentication code soon.

**Comment by lavalamp-** [comment]
This is now fixed in https://github.com/lavalamp-/ws-backend-community/commit/89f6a87f783972da7fd8c5f6fb95293283d00c82

A new configuration value has been added:

```
[Elasticsearch]

es_use_http_auth = True
```

This value is then checked when instantiating the Elasticsearch client:

```
def __get_standard_es_connection(self):
    """
    Create a new standard Elasticsearch connection and return it.
    :return: An Elasticsearch connection.
    """
    if config.http_proxy_enabled:
        proxies = {
            "http": config.http_proxy,
            "https": config.http_proxy,
        }
    else:
        proxies = {}
    if config.es_use_http_auth:
        return Elasticsearch(
            [config.es_url],
            http_auth=(config.es_username, config.es_password),
            connection_class=WsElasticsearchConnection,
            proxies=proxies,
        )
    else:
        return Elasticsearch(
            [config.es_url],
            connection_class=WsElasticsearchConnection,
            proxies=proxies,
        )
```

**Comment by cjohnson-bf** [comment]
Great, thanks very much, this was in fact my issue.
