### ISSUE TITLE
Tasknode Test Errors

### ISSUE THREAD

**Issue by cjohnson-bf** [lavalamp-/ws-docker-community#4]
Getting some errors running the tasknode tests. I've glanced at the code but it's still not obvious what the issue is. Any hints as to what might be causing this? Let me know if I can provide any more info. 

Thanks!

```
root@1cae3ff86265:/ws-backend# python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
Now populating database and Elasticsearch...
Performining bulk update on Elasticsearch...
Bulk query completed. Sleeping for 1 second to allow Elasticsearch time for indexing.
Test environment populated successfully.
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................No handlers could be found for logger "rest.views.elasticsearch.models.mixin"
.........................................................................................................................................................................................................................................................................................................................../usr/local/lib/python2.7/site-packages/amqp/connection.py:304: AMQPDeprecationWarning: The .frame_writer attribute on the connection was accessed before
the connection was established.  This is supported for now, but will
be deprecated in amqp 2.2.0.

Since amqp 2.0 you have to explicitly call Connection.connect()
before using the connection.

  W_FORCE_CONNECT.format(attr=attr)))
...........................................................................................................FF.........................................................................................................................................................
======================================================================
FAIL: test_forms (tests.lib_tests.inspection_tests.analysis_tests.test_web.TestWebScanInspector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ws-backend/tests/lib_tests/inspection_tests/analysis_tests/test_web.py", line 116, in test_forms
    self.assertGreater(len(self.inspector.forms), 0)
AssertionError: 0 not greater than 0

======================================================================
FAIL: test_landing_resource_exists (tests.lib_tests.inspection_tests.analysis_tests.test_web.TestWebScanInspector)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ws-backend/tests/lib_tests/inspection_tests/analysis_tests/test_web.py", line 109, in test_landing_resource_exists
    self.assertIsNotNone(self.inspector.landing_resource)
AssertionError: unexpectedly None

----------------------------------------------------------------------
Ran 1028 tests in 68.673s

FAILED (failures=2)
Now tearing test environment down...
Web Sight test environment torn down successfully.
Destroying test database for alias 'default'...
```

**Comment by lavalamp-** [comment]
These errors can be safely ignored at this point - it's an error in the unit test and not the code. I've been meaning to fix them but may just remove them until I've got time.
